service: frontend-service
runtime: nodejs20
instance_class: F1

handlers:
  - url: /(.*\.(css|js|png|jpg|ico|json|svg|woff2?|txt|webp|ttf))
    static_files: build/\1
    upload: build/.*\.(css|js|png|jpg|ico|json|svg|woff2?|txt|webp|ttf)
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always