steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be-rest", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be-rest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "be-rest",
        "--image",
        "gcr.io/$PROJECT_ID/tcc-be-rest",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "DB_HOST=${_DB_HOST},
        DB_PORT=${_DB_PORT},
        DB_USER=${_DB_USER},
        DB_PASSWORD=${_DB_PASSWORD},
        DB_NAME=${_DB_NAME},
        JWT_SECRET=${_JWT_SECRET},
        PORT=${_PORT},
        GCP_BUCKET_NAME=${_GCP_BUCKET_NAME},
        GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS},
        GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
